"""
Repository interfaces — contracts the application layer depends on.
Only domain types cross this boundary.
"""
from typing import Optional, Protocol, runtime_checkable
from app.domain.entities import Book, Page, BookStatus, PageStatus


@runtime_checkable
class BookRepository(Protocol):
    async def get_by_id(self, book_id: str) -> Optional[Book]: ...
    async def get_all(self) -> list[Book]: ...
    async def save(self, book: Book) -> Book: ...
    async def update(self, book: Book) -> None: ...


@runtime_checkable
class PageRepository(Protocol):
    async def get(self, book_id: str, page_number: int) -> Optional[Page]: ...
    async def get_all_for_book(self, book_id: str) -> list[Page]: ...
    async def save(self, page: Page) -> Page: ...
    async def update(self, page: Page) -> None: ...
    async def bulk_insert(self, pages: list[Page]) -> None: ...
