"""
Port — what the application needs from the file system.
Infrastructure implements this; domain and application only import from here.
"""
from typing import Optional, Protocol, runtime_checkable
from pathlib import Path


@runtime_checkable
class FileStoragePort(Protocol):
    def setup_book_dir(self, book_id: str) -> None: ...

    def save_pdf(self, book_id: str, filename: str, data: bytes) -> None: ...

    def get_page_image_url(self, book_id: str, page_number: int) -> str: ...

    def read_page_ocr_content(self, book_id: str, page_number: int) -> Optional[str]: ...

    def write_page_ocr_content(self, book_id: str, page_number: int, content: str) -> None: ...

    def get_pdf_path(self, book_id: str) -> Path: ...

    def get_compiled_pdf_path(self, book_id: str) -> Optional[Path]: ...

    def read_book_metadata(self, book_id: str) -> dict: ...
